# Generated by Django 6.0.1 on 2026-02-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='craeted',
            new_name='created',
        ),
    ]
